<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["clientes/index", "Go Back"]); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(["clientes/new", "Create "]); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Id</th>
            <th>Trabaja</th>
            <th>Estudia</th>
            <th>Direccion</th>
            <th>Nombredepadre</th>
            <th>Nombredemadre</th>
            <th>Telefono</th>
            <th>Activo</th>
            <th>Iduser</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $cliente): ?>
            <tr>
                <td><?php echo $cliente->getId() ?></td>
            <td><?php echo $cliente->getTrabaja() ?></td>
            <td><?php echo $cliente->getEstudia() ?></td>
            <td><?php echo $cliente->getDireccion() ?></td>
            <td><?php echo $cliente->getNombredepadre() ?></td>
            <td><?php echo $cliente->getNombredemadre() ?></td>
            <td><?php echo $cliente->getTelefono() ?></td>
            <td><?php echo $cliente->getActivo() ?></td>
            <td><?php echo $cliente->getIduser() ?></td>

                <td><?php echo $this->tag->linkTo(["clientes/edit/" . $cliente->getId(), "Edit"]); ?></td>
                <td><?php echo $this->tag->linkTo(["clientes/delete/" . $cliente->getId(), "Delete"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo(["clientes/search", "First", 'class' => 'page-link']) ?></li>
                <li><?php echo $this->tag->linkTo(["clientes/search?page=" . $page->before, "Previous", 'class' => 'page-link']) ?></li>
                <li><?php echo $this->tag->linkTo(["clientes/search?page=" . $page->next, "Next", 'class' => 'page-link']) ?></li>
                <li><?php echo $this->tag->linkTo(["clientes/search?page=" . $page->last, "Last", 'class' => 'page-link']) ?></li>
            </ul>
        </nav>
    </div>
</div>
