<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <hr>
    <button class="btn btn-default">
        <?php echo $this->tag->linkTo(["Inventario/new", "Agregar nuevo articulo al inventario"]) ?>
    </button>

    <hr>
    <h1>
        Buscar articulo en inventario
    </h1>

</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        [
            "Inventario/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldCodigoArticulo" class="col-sm-2 control-label">Codigo de Articulo</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["codigo_articulo", "type" => "number", "class" => "form-control", "id" => "fieldCodigoArticulo"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldIdInventario" class="col-sm-2 control-label">Id de Inventario</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["id_inventario", "type" => "number", "class" => "form-control", "id" => "fieldIdInventario"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCantidad" class="col-sm-2 control-label">Cantidad</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["cantidad", "type" => "number", "class" => "form-control", "id" => "fieldCantidad"]) ?>
    </div>
</div>

<hr>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Buscar", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
