<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <button class="btn btn-default">
            <?php echo $this->tag->linkTo(["inventario", "Regresar"]) ?>
        </button>
    </nav>
</div>

<hr>

<div class="page-header">
    <h1>
        Agregar Articulo
    </h1>
</div>

<hr>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "inventario/create",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldIdInventario" class="col-sm-2 control-label">Id de Inventario</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["id_inventario", "type" => "number", "class" => "form-control", "id" => "fieldIdInventario"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCantidad" class="col-sm-2 control-label">Cantidad</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["cantidad", "type" => "number", "class" => "form-control", "id" => "fieldCantidad"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCodigoArticulo" class="col-sm-2 control-label">Codigo de Articulo</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["codigo_articulo", "type" => "number", "class" => "form-control", "id" => "fieldCodigoArticulo"]) ?>
    </div>
</div>

<hr>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Guardar", "class" => "btn btn-success"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
