<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["Inventario", "Go Back"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Create Inventario
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "Inventario/create",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldCodigoArticulo" class="col-sm-2 control-label">Codigo Of Articulo</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["codigo_articulo", "type" => "number", "class" => "form-control", "id" => "fieldCodigoArticulo"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldIdInventario" class="col-sm-2 control-label">Id Of Inventario</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["id_inventario", "type" => "number", "class" => "form-control", "id" => "fieldIdInventario"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCantidad" class="col-sm-2 control-label">Cantidad</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["cantidad", "type" => "number", "class" => "form-control", "id" => "fieldCantidad"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
