<?php 
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>
<br>
<div class="row">
    <nav>
        <button class="btn btn-default">
            <?php echo $this->tag->linkTo(["articulo/search", "Regresar"]) ?>
        </button>
    </nav>
</div>

<hr>

<div class="page-header">
    <h1>
        Agregar nuevo articulo al inventario
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "Inventario/create",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldCodigoArticulo" class="col-sm-2 control-label"><b>Codigo de Articulo</b></label>
     
    <div readonly class="col-sm-10">
        <input readonly   
        <?php echo $this->tag->textField(["codigo_articulo", "type" => "number", "class" => "form-control", "id" => "fieldCodigoArticulo"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldIdInventario" class="col-sm-2 control-label"><b>Id de Inventario</b></label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["id_inventario", "type" => "number", "class" => "form-control", "id" => "fieldIdInventario"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCantidad" class="col-sm-2 control-label"><b>Cantidad</b></label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["cantidad", "type" => "number", "class" => "form-control", "id" => "fieldCantidad"]) ?>
    </div>
</div>

<hr>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Guardar", "class" => "btn btn-success"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
