<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>
<?php use Phalcon\Escaper;
use Phalcon\Flash\Direct;

$escaper = new Escaper();
$flash = new Direct($escaper);
use venta\Articulo;

?>

<div class="row">
    <nav>
        <button class="btn btn-default">
            <?php echo $this->tag->linkTo(["inventario/index", "Regresar"]); ?>
        </button>
        <button class="btn btn-default">
            <?php echo $this->tag->linkTo(["inventario/new", "Agregar"]); ?>
        </button>
    </nav>
</div>

<div class="page-header">
    <h1>Resultado de la busqueda</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead class="thead-dark">
            <tr>
                <th>Id de Inventario</th>
                <th>Cantidad</th>
                <th>Codigo de Articulo</th>
                <th>Articulo</th>
                <th>Opciones</th>
            
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $inventario): ?>
            <tr>
                <td><?php echo $inventario->id_inventario ?></td>
                <td><?php echo $inventario->cantidad ?></td>
                <td><?php echo $inventario->codigo_articulo ?></td>
                    <?php
                        $articulo = Articulo::findFirstBycodigo_articulo($inventario->codigo_articulo); 
                    ?>
                <td><?php echo $articulo->titulo ?></td>

                <td>
                    <button class="btn btn-default">
                    <?php echo $this->tag->linkTo(["inventario/edit/" . $inventario->id_inventario, "Editar"]); ?>
                    </button>    
                
                    <button class="btn btn-danger">
                    <?php echo $this->tag->linkTo(["inventario/delete/" . $inventario->id_inventario, "Eliminar"]); ?>
                    </button>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo(["inventario/search", "Primero", 'class' => 'page-link']) ?></li>
                <li><?php echo $this->tag->linkTo(["inventario/search?page=" . $page->before, "Anterior", 'class' => 'page-link']) ?></li>
                <li><?php echo $this->tag->linkTo(["inventario/search?page=" . $page->next, "Siguiente", 'class' => 'page-link']) ?></li>
                <li><?php echo $this->tag->linkTo(["inventario/search?page=" . $page->last, "Ultimo", 'class' => 'page-link']) ?></li>
            </ul>
        </nav>
    </div>
</div>
