<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>
<br><br>
<div class="row">
    <nav>
        <ul class="pager">
            <button class="btn btn-default" class="previous"><?php echo $this->tag->linkTo(["categoria/search", "Atras"]) ?></button>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Editar Categoria
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "categoria/save",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>
<br>
<div class="form-group">
    <label for="fieldCodigoDepartamento" class="col-sm-4 control-label"><b>Codigo de Departamento</b></label>
    <div class="col-sm-10">
    <input readonly <?php echo $this->tag->textField(["codigo_departamento", "type" => "number", "class" => "form-control", "id" => "fieldCodigoDepartamento"]) ?> 
    </div>
</div>

<div class="form-group">
    <label for="fieldCodigoCategoria" class="col-sm-2 control-label"><b>Codigo de Categoria</b></label>
    <div class="col-sm-10">
    <input readonly <?php echo $this->tag->textField(["codigo_categoria", "type" => "number", "class" => "form-control", "id" => "fieldCodigoCategoria"]) ?> 
        </div>
    </div>
</div>

<div class="form-group">
    <label for="fieldNombreCategoria" class="col-sm-2 control-label"><b>Nombre de Categoria</b></label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["nombre_categoria", "size" => 30, "class" => "form-control", "id" => "fieldNombreCategoria"]) ?>
    </div>
</div>




<?php echo $this->tag->hiddenField("id") ?>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Guardar", "class" => "btn btn-success"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
