<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>
<br><br>
<div class="row">
    <nav>
        <ul class="pager">
            <button class="btn btn-default" class="previous"><?php echo $this->tag->linkTo(["categoria/search", "Atras"]) ?></button>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        ESTA SEGURO QUE DESEA ELIMINAR ESTA CATEGORIA?

    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "categoria/delete",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldCodigoCategoria" class="col-sm-2 control-label"><b>Codigo de Categoria</b></label>
    <div  class="col-sm-10">
        <?php echo $this->tag->textField(["codigo_categoria", "type" => "number", "class" => "form-control", "id" => "fieldCodigoCategoria"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldNombreCategoria" class="col-sm-4 control-label"><b>Nombre de Categoria</b></label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["nombre_categoria", "size" => 30, "class" => "form-control", "id" => "fieldNombreCategoria"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCodigoDepartamento" class="col-sm-4 control-label"><b>Codigo de Departamento</b></label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["codigo_departamento", "type" => "number", "class" => "form-control", "id" => "fieldCodigoDepartamento"]) ?>
    </div>
</div>

        <button class="btn btn-danger"><?php echo $this->tag->linkTo(["categoria/delete/" . $codigo_categoria, "Borrar"]); ?></button>
    </tr>
