<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Search categoria
    </h1>
    <p>
        <?php echo $this->tag->linkTo(["categoria/new", "Create categoria"]) ?>
    </p>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        [
            "categoria/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldCodigoCategoria" class="col-sm-2 control-label">Codigo Of Categoria</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["codigo_categoria", "type" => "number", "class" => "form-control", "id" => "fieldCodigoCategoria"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldNombreCategoria" class="col-sm-2 control-label">Nombre Of Categoria</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["nombre_categoria", "size" => 30, "class" => "form-control", "id" => "fieldNombreCategoria"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCodigoDepartamento" class="col-sm-2 control-label">Codigo Of Departamento</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["codigo_departamento", "type" => "number", "class" => "form-control", "id" => "fieldCodigoDepartamento"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Search", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
