<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>
<br><br>

<button class="btn btn-default">
        <?php echo $this->tag->linkTo(["/", "Atras"]) ?>
    </button>
<div class="page-header">
    <h1>
        Buscar categoria
    </h1>
    
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        [
            "categoria/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>
<br>
<div class="form-group">
    <label for="fieldCodigoCategoria" class="col-sm-2 control-label"><b>Codigo de Categoria</b></label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["codigo_categoria", "type" => "number", "class" => "form-control", "id" => "fieldCodigoCategoria"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldNombreCategoria" class="col-sm-4 control-label"><b>Nombre de Categoria</b></label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["nombre_categoria", "size" => 30, "class" => "form-control", "id" => "fieldNombreCategoria"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCodigoDepartamento" class="col-sm-4 control-label"><b>Codigo de Departamento</b></label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["codigo_departamento", "type" => "number", "class" => "form-control", "id" => "fieldCodigoDepartamento"]) ?>
    </div>
</div>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Buscar", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
