<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <button class="btn btn-default" class="previous"><?php echo $this->tag->linkTo(["categoria/search", "Atras"]) ?></button>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Create categoria
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "categoria/create",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldCodigoCategoria" class="col-sm-2 control-label">Codigo de Categoria</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["codigo_categoria", "type" => "number", "class" => "form-control", "id" => "fieldCodigoCategoria"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldNombreCategoria" class="col-sm-2 control-label">Nombre de Categoria</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["nombre_categoria", "size" => 30, "class" => "form-control", "id" => "fieldNombreCategoria"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCodigoDepartamento" class="col-sm-2 control-label">Codigo de Departamento</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["codigo_departamento", "type" => "number", "class" => "form-control", "id" => "fieldCodigoDepartamento"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Guardar", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
