<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>
<br><br>
<div class="row">
    <nav>
        <ul class="pager">
            <button class="btn btn-default" class="previous"><?php echo $this->tag->linkTo(["categoria/index", "Atras"]); ?></button>
            <button class="btn btn-default" class="next"><?php echo $this->tag->linkTo(["categoria/new", "Crear Categoria "]); ?></button>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Ver Categorias</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Codigo de Categoria</th>
            <th>Nombre de Categoria</th>
            <th>Codigo de Departamento</th>

                <th style="text-align: center" colspan="2">Acciones</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $categoria): ?>
            <tr>
                <td><?php echo $categoria->getCodigoCategoria() ?></td>
            <td><?php echo $categoria->getNombreCategoria() ?></td>
            <td><?php echo $categoria->getCodigoDepartamento() ?></td>

                <td><?php echo $this->tag->linkTo(["categoria/edit/" . $categoria->getCodigoCategoria(), "Editar"]); ?></td>
                <td><?php echo $this->tag->linkTo(["categoria/delete/" . $categoria->getCodigoCategoria(), "Borrar"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo(["categoria/search", "Primera Pagina", 'class' => 'page-link']) ?></li>
                <li><?php echo $this->tag->linkTo(["categoria/search?page=" . $page->before, "...", 'class' => 'page-link']) ?></li>
                <li><?php echo $this->tag->linkTo(["categoria/search?page=" . $page->next, "Siguiente Pagina", 'class' => 'page-link']) ?></li>
                <li><?php echo $this->tag->linkTo(["categoria/search?page=" . $page->last, "Ultima Pagina", 'class' => 'page-link']) ?></li>
            </ul>
        </nav>
    </div>
</div>
