<meta charset="utf-8">


  <script type="text/javascript" charset="utf8" src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js"></script>
  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/jq-3.3.1/dt-1.10.20/datatables.min.css"/>

<script type="text/javascript" src="https://cdn.datatables.net/v/dt/jq-3.3.1/dt-1.10.20/datatables.min.js" ></script>
    <script>

      $(document).ready(function(){
        $.noConflict();
        var table = $('#table_id').dataTable({
          "language": {
            "decimal": "",
        "emptyTable": "No hay información",
        "info": "Mostrando _START_ a _END_ de _TOTAL_ Entradas",
        "infoEmpty": "Mostrando 0 to 0 of 0 Entradas",
        "infoFiltered": "(Filtrado de _MAX_ total entradas)",
        "infoPostFix": "",
        "thousands": ",",
        "lengthMenu": "Mostrar _MENU_ Entradas",
        "loadingRecords": "Cargando...",
        "processing": "Procesando...",
        "search": "Buscar:",
        "zeroRecords": "Sin resultados encontrados",
        "paginate": {
            "first": "Primero",
            "last": "Ultimo",
            "next": "Siguiente",
            "previous": "Anterior"
        }
    },
        "pagingType": "full_numbers"});

    });
    </script>

<style>
  table th {
        text-align: center;
        }
    table tr {
            text-align: center;
        }
</style>

<br>
<div class="page-header">

    <table>
        <tr>
            <td rowspan="2"><img src="files/logo.jpeg" width="" height="30%"></td>
            <td><h1><b>Bienvenido a la Tienda de Too!<b></h1></td>
        </tr>
        <tr>
            <td><h2>Podras encontrar muchos articulos que te pueden ser de mucha utilidad!</h2></td>
        </tr>
    </table>

</div>


<!--   ----------------------------------------------------------------------------------->

<!--<p>This page is located at <code>views/index/index.phtml</code></p>-->
<br>
<div class="row">
    <table style="width: 1200px" id="table_id" class="table" bordes:black 1px solid; class="table table-bordered table-striped">
        <thead class="thead-dark">
            <tr>
            <th width="15%"></th>
            <th width="15%" style="text-align: center;">Descripcion</th>
            <!--<th width="5%">Codigo</th>
            <th width="15%" style="text-align: center;">Titulo</th>-->
            <th width="7%">Precio</th>

            <th width="7%">Descuento</th>
            <th width="7%">Envio</th>



            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $articulo): ?>
            <tr>
                <!--<td><?php echo $articulo->getCodigoCategoria() ?></td>-->
                <td><img src="files/<?php echo $articulo->getCodigoArticulo().'/'.$articulo->getRuta();?>"></td>
            <!--<td><?php echo "<img src='files/".$articulo->getCodigoArticulo().'/'.$articulo->getRuta() ?></td>-->

            <td><b>Codigo:</b><?php echo $articulo->getCodigoArticulo() ?><br><b>Titulo:</b><?php echo $articulo->getTitulo() ?><br><b>Descripcion:</b><br><?php echo $articulo->getDescripcion() ?></td>
            <!--<td><?php echo $articulo->getCodigoArticulo() ?></td>
            <td><?php echo $articulo->getTitulo() ?></td>-->
            <td>$<?php echo $articulo->getPrecio() ?></td>

            <td>$<?php echo $articulo->getDescuento() ?></td>
            <td><?php echo $articulo->getEnvio() ?></td>



            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo(["/index", "Primera pagina", 'class' => 'page-link']) ?></li>
                <li><?php echo $this->tag->linkTo(["/index?page=" . $page->before, "....", 'class' => 'page-link']) ?></li>
                <li><?php echo $this->tag->linkTo(["/index?page=" . $page->next, "Siguiente Pagina", 'class' => 'page-link']) ?></li>
                <li><?php echo $this->tag->linkTo(["/index?page=" . $page->last, "Ultima Pagina", 'class' => 'page-link']) ?></li>
            </ul>
        </nav>
    </div>
</div>
