<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>


<head>
<meta charset="utf-8">
    <script src="http://code.jquery.com/jquery-1.9.1.js" type="text/javascript"></script>
    <script src="jquery.maskedinput.min.js" type="text/javascript"></script>

<script>
jQuery(function($){
     $("#fieldFechanacimiento").mask("9999/99/99");
});
</script>
</head>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["users", "Go Back"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Create users
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "users/create",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldUsername" class="col-sm-2 control-label">Username</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["username", "size" => 30, "class" => "form-control", "id" => "fieldUsername"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldPassword" class="col-sm-2 control-label">Password</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["password", "size" => 30, "class" => "form-control", "id" => "fieldPassword"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldEmail" class="col-sm-2 control-label">Email</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["email", "size" => 30, "class" => "form-control", "id" => "fieldEmail"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldFechanacimiento" class="col-sm-2 control-label">Fecha de nacimiento</label>
    <div class="col-sm-10">
        <input placeholder="AAAA-MM-DD "
        <?php echo $this->tag->textField(["fechanacimiento", "type" => "date", "class" => "form-control", "id" => "fieldFechanacimiento"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldNombre" class="col-sm-2 control-label">Nombre</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["nombre", "size" => 30, "class" => "form-control", "id" => "fieldNombre"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldSexo" class="col-sm-2 control-label">Sexo</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["sexo", "size" => 30, "class" => "form-control", "id" => "fieldSexo"]) ?>
    </div>
</div>


<div class="form-group">
    <label for="fieldIdrol" class="col-sm-2 control-label"></label>
    <div class="col-sm-10">
        <input readonly value="3" type="hidden"
        <?php echo $this->tag->textField(["idrol", "type" => "number", "class" => "form-control", "id" => "fieldIdrol"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
