<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>
<br>
<div class="row">
    <nav>
        <button class="btn btn-default">
            <?php echo $this->tag->linkTo(["departamento", "Regresar"]) ?>
        </button>
    </nav>
</div>
<hr>
<div class="page-header">
    <h1>
        Editar departamento
    </h1>
</div>
<hr>
<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "departamento/save",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>
 

<?php

    use venta\Departamento;
    use venta\Categoria;
    /*PRINT("DFFFFFFFFF");
    print($codigo_departamento);*/


    $categoria = Categoria::findFirstBycodigo_departamento($codigo_departamento);

    if ($categoria->codigo_departamento == $codigo_departamento) { ?>
        <div class="form-group">
    <label for="fieldCodigoDepartamento" class="col-sm-4 control-label"><b>Codigo de Departamento</b></label>
    <div class="col-sm-10">

    <input readonly <?php echo $this->tag->textField(["codigo_departamento", "type" => "number", "class" => "form-control", "id" => "fieldCodigoDepartamento"]) ?> 
    
        
    </div>
</div>

   <?php } else { ?>
<div class="form-group">
    <label for="fieldCodigoDepartamento" class="col-sm-4 control-label"><b>Codigo de Departamento</b></label>
    <div class="col-sm-10">

    <input <?php echo $this->tag->textField(["codigo_departamento", "type" => "number", "class" => "form-control", "id" => "fieldCodigoDepartamento"]) ?> 
    
        
    </div>
</div>

   <?php } ?>







<div class="form-group">
    <label for="fieldNombreDepartamento" class="col-sm-4 control-label"><b>Nombre de Departamento</b></label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["nombre_departamento", "size" => 30, "class" => "form-control", "id" => "fieldNombreDepartamento"]) ?>
    </div>
</div>
<hr>

<?php echo $this->tag->hiddenField("id") ?>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Guardar", "class" => "btn btn-success"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm();?>