<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <hr>
    <button class="btn btn-default">
        <?php echo $this->tag->linkTo(["departamento/new", "Crear nuevo departamento"]) ?>
    </button>

    <hr>
    <h2>
        Buscar departamento
    </h2>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        [
            "departamento/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldCodigoDepartamento" class="col-sm-4 control-label">Codigo de Departamento</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["codigo_departamento", "type" => "number", "class" => "form-control", "id" => "fieldCodigoDepartamento"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldNombreDepartamento" class="col-sm-4 control-label">Nombre de Departamento</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["nombre_departamento", "size" => 30, "class" => "form-control", "id" => "fieldNombreDepartamento"]) ?>
    </div>
</div>

<hr>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Buscar", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
