<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<meta charset="utf-8">


  <script type="text/javascript" charset="utf8" src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js"></script>
  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/jq-3.3.1/dt-1.10.20/datatables.min.css"/>

<script type="text/javascript" src="https://cdn.datatables.net/v/dt/jq-3.3.1/dt-1.10.20/datatables.min.js" ></script>
    <script>

      $(document).ready(function(){
        $.noConflict();
        var table = $('#table_id').dataTable({
          "language": {
            "decimal": "",
        "emptyTable": "No hay información",
        "info": "Mostrando _START_ a _END_ de _TOTAL_ Entradas",
        "infoEmpty": "Mostrando 0 to 0 of 0 Entradas",
        "infoFiltered": "(Filtrado de _MAX_ total entradas)",
        "infoPostFix": "",
        "thousands": ",",
        "lengthMenu": "Mostrar _MENU_ Entradas",
        "loadingRecords": "Cargando...",
        "processing": "Procesando...",
        "search": "Buscar:",
        "zeroRecords": "Sin resultados encontrados",
        "paginate": {
            "first": "Primero",
            "last": "Ultimo",
            "next": "Siguiente",
            "previous": "Anterior"
        }
    },
        "pagingType": "full_numbers"});

    });
    </script>

<style>
  table th {
        text-align: center;
        }
    table tr {
            text-align: center;
        }
</style>


<?php use Phalcon\Tag;  ?>
<?php use Phalcon\Escaper;
use Phalcon\Flash\Direct;

$escaper = new Escaper();
$flash = new Direct($escaper);

?>

<?php
                  if ($this->session->has('IS_LOGIN'))
                            { ?>
<br>
<br>
<div class="row">
    <nav>
        <button class="btn btn-default">
            <?php echo $this->tag->linkTo(["/", "Regresar"]) ?>
        </button>
        <button class="btn btn-default">
            <?php echo $this->tag->linkTo(["departamento/new", "Crear"]) ?>
        </button>
    </nav>
</div>

<div class="page-header">
    <h1>Ver Departamentos</h1>
</div>

<?php echo $this->getContent(); ?>

    <table id="table_id" class="table">
        <thead class="thead-dark">
            <tr>
                <th scope="col">Codigo de Departamento</th>
                <th scope="col">Nombre de Departamento</th>
                <th scope="col"></th>
                <th scope="col">Opciones</th>
                <th scope="col"></th>

            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $departamento): ?>
            <tr>
                <td><?php echo $departamento->getCodigoDepartamento() ?></td>
                <td><?php echo $departamento->getNombreDepartamento() ?></td>

                <td>
                    <button class="btn btn-default">
                        <?php echo $this->tag->linkTo(["departamento/edit/" . $departamento->getCodigoDepartamento(), "Editar"]); ?>
                    </button>
                </td>
                <td>
                    <button class="btn btn-danger">
                        <?php echo $this->tag->linkTo(["departamento/eliminar/" . $departamento->getCodigoDepartamento(), "Eliminar"]); ?>
                    </button>
                </td>
                <td>
                    <button class="btn btn-default">
                        <?php echo $this->tag->linkTo(["categoria/new/" . $departamento->getCodigoDepartamento(), "Agregar Categoria"]);
                        ?>
                    </button>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo(["departamento/search", "Primero", 'class' => 'page-link']) ?></li>
                <li><?php echo $this->tag->linkTo(["departamento/search?page=" . $page->before, "Anterior", 'class' => 'page-link']) ?></li>
                <li><?php echo $this->tag->linkTo(["departamento/search?page=" . $page->next, "Siguiente", 'class' => 'page-link']) ?></li>
                <li><?php echo $this->tag->linkTo(["departamento/search?page=" . $page->last, "Ultimo", 'class' => 'page-link']) ?></li>
            </ul>
        </nav>
    </div>
</div>
<?php   } ?>