<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag;  ?>
<?php use Phalcon\Escaper;
use Phalcon\Flash\Direct;

$escaper = new Escaper();
$flash = new Direct($escaper);

?>

<div class="row">
    <nav>
        <button class="btn btn-default">
            <?php echo $this->tag->linkTo(["departamento", "Regresar"]) ?>
        </button>
        <button class="btn btn-default">
            <?php echo $this->tag->linkTo(["departamento/new", "Crear"]) ?>
        </button>
    </nav>
</div>

<div class="page-header">
    <h1>Resultado de la busqueda</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead class="thead-dark">
            <tr>
                <th>Codigo de Departamento</th>
                <th>Nombre de Departamento</th>
                <th>Opciones</th>
                
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $departamento): ?>
            <tr>
                <td><?php echo $departamento->getCodigoDepartamento() ?></td>
                <td><?php echo $departamento->getNombreDepartamento() ?></td>

                <td>
                    <button class="btn btn-default">
                        <?php echo $this->tag->linkTo(["departamento/edit/" . $departamento->getCodigoDepartamento(), "Editar"]); ?>
                    </button>
                
                    <button class="btn btn-danger">
                        <?php echo $this->tag->linkTo(["departamento/eliminar/" . $departamento->getCodigoDepartamento(), "Eliminar"]); ?>
                    </button>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo(["departamento/search", "Primero", 'class' => 'page-link']) ?></li>
                <li><?php echo $this->tag->linkTo(["departamento/search?page=" . $page->before, "Anterior", 'class' => 'page-link']) ?></li>
                <li><?php echo $this->tag->linkTo(["departamento/search?page=" . $page->next, "Siguiente", 'class' => 'page-link']) ?></li>
                <li><?php echo $this->tag->linkTo(["departamento/search?page=" . $page->last, "Ultimo", 'class' => 'page-link']) ?></li>
            </ul>
        </nav>
    </div>
</div>
