<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */

/*$id = $_GET['codigo_articulo'];

echo '<pre>';
print_r($_FILES); 
var_dump($_FILES);
echo '</pre>';

echo '<pre>';
print_r($_GET);
echo '</pre>';*/
?>
<br><br>
<div class="row">
    <nav>
        <ul class="pager">
            <button class="btn btn-default" class="previous"><?php echo $this->tag->linkTo(["articulo/search", "Regresar"]) ?></button>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Editar articulo
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "articulo/save",
            "autocomplete" => "off",
            "class" => "form-horizontal",
            "enctype" => "multipart/form-data",
            "method" => "post",
            "action" => "guardar.php"
        ]
    );
?>


<?php

    use venta\Inventario;
    use venta\Articulo;
    /*PRINT("DFFFFFFFFF");
    print($codigo_departamento);*/


    $inventario = Inventario::findFirstBycodigo_articulo($codigo_articulo);
    

    if ($inventario->codigo_articulo == $codigo_articulo) { ?>

        <div class="form-group">
            <label for="fieldCodigoArticulo" class="col-sm-2 control-label"><b>Codigo de Articulo</b></label>
            <div class="col-sm-10">
                <input readonly <?php echo $this->tag->textField(["codigo_articulo", "type" => "number", "class" => "form-control", "id" => "fieldCodigoArticulo"]) ?> 
    </div>
</div>

   <?php } else { ?>
    <div class="form-group">
        <label for="fieldCodigoArticulo" class="col-sm-2 control-label"><b>Codigo de Articulo</b></label>
        <div class="col-sm-10">
            <input <?php echo $this->tag->textField(["codigo_articulo", "type" => "number", "class" => "form-control", "id" => "fieldCodigoArticulo"]) ?> 
    </div>
</div>

   <?php } ?>    



<div class="form-group">
    <label for="fieldCodigoCategoria" class="col-sm-2 control-label"><b>Codigo de Categoria</b></label>

    <div class="col-sm-10">
    <input readonly <?php echo $this->tag->textField(["codigo_categoria", "type" => "number", "class" => "form-control", "id" => "fieldCodigoCategoria"]) ?>  
    </div>
    
    </div>


    




<div class="form-group">
    <label for="fieldTitulo" class="col-sm-2 control-label"><b>Titulo</b></label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["titulo", "size" => 30, "class" => "form-control", "id" => "fieldTitulo"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldPrecio" class="col-sm-2 control-label"><b>Precio</b></label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["precio", "size" => 30, "class" => "form-control", "id" => "fieldPrecio"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDescripcion" class="col-sm-2 control-label"><b>Descripcion</b></label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["descripcion", "size" => 30, "class" => "form-control", "id" => "fieldDescripcion"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDescuento" class="col-sm-2 control-label"><b>Descuento</b></label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["descuento", "size" => 30, "class" => "form-control", "id" => "fieldDescuento"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldEnvio" class="col-sm-2 control-label"><b>Envio</b></label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["envio", "size" => 30, "class" => "form-control", "id" => "fieldEnvio"]) ?>
    </div>
</div>

<div class="form-group">
    
    <label for="archivo" class="col-sm-2 control-label"><b>Imagen</b></label>
    <div class="col-sm-10">
        <input class="form-control" type="file" id="ruta" name="ruta">
        <img src="files/<?php echo "codigo_articulo".'/'."ruta";?>">
        <!--<?php echo $this->tag->fileField(["ruta", "size" => 30, "class" => "form-control", "id" => "fieldEnvio"]) ?>-->

       <!--<?php

       echo "<img src=\files\1\descarga.png>";
       ?>-->
       <img src="/descarga.png">
      <!-- <?php 
                            $path = '/'.$ruta;
                            if(file_exists($path)){
                                $directorio = opendir($path);
                                while ($archivo = readdir($directorio))
                                {
                                    if (!is_dir($archivo)){
                                        echo "<div data='".$path."/".$archivo."'><a href='".$path."/".$archivo."' title='Ver Archivo Adjunto'><span class='glyphicon glyphicon-picture'></span></a>";
                                        echo "$archivo <a href='#' class='delete' title='Ver Archivo Adjunto' ><span class='glyphicon glyphicon-trash' aria-hidden='true'></span></a></div>";
                                        echo "<img src='files/$id/$archivo' width='300' />";
                                    }
                                }
                            }
                            
                        ?> -->
       
    </div>
    
</div>


<?php echo $this->tag->hiddenField("id") ?>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Guardar", "class" => "btn btn-success"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
