<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
echo '<pre>';
print_r($_FILES);
var_dump($_FILES);
echo '</pre>';

echo '<pre>';
print_r($_POST);
echo '</pre>';
?>
?>

<div class="page-header"><br><br>
    <button class="btn btn-default">
        <?php echo $this->tag->linkTo(["articulo/new", "Crear articulo"]) ?>
    </button>
    <h1>
        Buscar Articulo
    </h1>
    
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        [
            "articulo/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldCodigoCategoria" class="col-sm-2 control-label">Codigo de Categoria</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["codigo_categoria", "type" => "number", "class" => "form-control", "id" => "fieldCodigoCategoria"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCodigoArticulo" class="col-sm-2 control-label">Codigo de Articulo</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["codigo_articulo", "type" => "number", "class" => "form-control", "id" => "fieldCodigoArticulo"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldTitulo" class="col-sm-2 control-label">Titulo</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["titulo", "size" => 30, "class" => "form-control", "id" => "fieldTitulo"]) ?>
    </div>
</div>

<!--<div class="form-group">
    <label for="fieldPrecio" class="col-sm-2 control-label">Precio</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["precio", "size" => 30, "class" => "form-control", "id" => "fieldPrecio"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDescripcion" class="col-sm-2 control-label">Descripcion</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["descripcion", "size" => 30, "class" => "form-control", "id" => "fieldDescripcion"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDescuento" class="col-sm-2 control-label">Descuento</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["descuento", "size" => 30, "class" => "form-control", "id" => "fieldDescuento"]) ?>
    </div>
</div>-->

<div class="form-group">
    <label for="fieldEnvio" class="col-sm-2 control-label">Envio</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["envio", "size" =>30, "class" => "form-control", "id" => "fieldEnvio"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Buscar", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
