<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */

echo '<pre>';
print_r($_FILES);
echo '</pre>';
?>
<br>
<div class="row">
    <nav>
        <ul class="pager">
            <button class="btn btn-default" class="previous"><?php echo $this->tag->linkTo(["articulo/search", "Atras"]) ?></button>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Crear articulo
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "articulo/create",
            "autocomplete" => "off",
            "class" => "form-horizontal",
            "enctype" => "multipart/form-data",
            "method" => "post",
            "action" => "guardar.php"
        ]
    );
?>
<!--<form data-ajax="false" class="form-horizontal" enctype="multipart/form-data" method="POST" action="guardar.php">-->
<div class="form-group">
    <label for="fieldCodigoCategoria" class="col-sm-2 control-label">Codigo de Categoria</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["codigo_categoria", "type" => "number", "class" => "form-control", "id" => "fieldCodigoCategoria"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCodigoArticulo" class="col-sm-2 control-label">Codigo de Articulo</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["codigo_articulo", "type" => "number", "class" => "form-control", "id" => "fieldCodigoArticulo"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldTitulo" class="col-sm-2 control-label">Titulo</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["titulo", "size" => 30, "class" => "form-control", "id" => "fieldTitulo"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldPrecio" class="col-sm-2 control-label">Precio</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["precio", "size" => 30, "class" => "form-control", "id" => "fieldPrecio"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDescripcion" class="col-sm-2 control-label">Descripcion</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["descripcion", "size" => 30, "class" => "form-control", "id" => "fieldDescripcion"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDescuento" class="col-sm-2 control-label">Descuento</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["descuento", "size" => 30, "class" => "form-control", "id" => "fieldDescuento"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldEnvio" class="col-sm-2 control-label">Envio</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["envio", "size" => 30, "class" => "form-control", "id" => "fieldEnvio"]) ?>
    </div>
</div>


<div class="form-group">
    
    <label for="archivo" class="col-sm-2 control-label">Archivo</label>
    <div class="col-sm-10">
        <input class="form-control" type="file" id="archivo" name="archivo">
       <!-- <?php echo $this->tag->fileField(["archivo", "size" => 30, "class" => "form-control", "id" => "fieldEnvio"]) ?>-->
        
       
    </div>
    
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <!--<button type="submit" class="btn btn-primary">guardarr</button>-->
        <?php echo $this->tag->submitButton(["Guardar", "class" => "btn btn-success"]) ?>
    </div>
</div>
<!--</form>-->

<?php echo $this->tag->endForm(); ?>
