<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<br><br>
<div class="row">
    
    <nav>
        <ul class="pager">
            <button class="btn btn-default" class="previous"><?php echo $this->tag->linkTo(["articulo/index", "Atras"]); ?></button>
            <button class="btn btn-default" class="next"><?php echo $this->tag->linkTo(["articulo/new", "Crear Articulo "]); ?></button>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Ver Articulos</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Codigo de Categoria</th>
            <th>Codigo de Articulo</th>
            <th>Titulo</th>
            <th>Precio</th>
            <th>Descripcion</th>
            <th>Descuento</th>
            <th>Envio</th>

                <th style="text-align: center" colspan="2">Acciones</th>
                
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $articulo): ?>
            <tr>
                <td><?php echo $articulo->getCodigoCategoria() ?></td>
            <td><?php echo $articulo->getCodigoArticulo() ?></td>
            <td><?php echo $articulo->getTitulo() ?></td>
            <td><?php echo $articulo->getPrecio() ?></td>
            <td><?php echo $articulo->getDescripcion() ?></td>
            <td><?php echo $articulo->getDescuento() ?></td>
            <td><?php echo $articulo->getEnvio() ?></td>

                <td><?php echo $this->tag->linkTo(["articulo/edit/" . $articulo->getCodigoCategoria(), "Editar"]); ?></td>
                <td><?php echo $this->tag->linkTo(["articulo/delete/" . $articulo->getCodigoCategoria(), "Borrar"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo(["articulo/search", "Primera pagina", 'class' => 'page-link']) ?></li>
                <li><?php echo $this->tag->linkTo(["articulo/search?page=" . $page->before, "....", 'class' => 'page-link']) ?></li>
                <li><?php echo $this->tag->linkTo(["articulo/search?page=" . $page->next, "Siguiente Pagina", 'class' => 'page-link']) ?></li>
                <li><?php echo $this->tag->linkTo(["articulo/search?page=" . $page->last, "Ultima Pagina", 'class' => 'page-link']) ?></li>
            </ul>
        </nav>
    </div>
</div>
