<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["articulo/index", "Go Back"]); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(["articulo/new", "Create "]); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Codigo Of Categoria</th>
            <th>Codigo Of Articulo</th>
            <th>Titulo</th>
            <th>Precio</th>
            <th>Descripcion</th>
            <th>Descuento</th>
            <th>Envio</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $articulo): ?>
            <tr>
                <td><?php echo $articulo->getCodigoCategoria() ?></td>
            <td><?php echo $articulo->getCodigoArticulo() ?></td>
            <td><?php echo $articulo->getTitulo() ?></td>
            <td><?php echo $articulo->getPrecio() ?></td>
            <td><?php echo $articulo->getDescripcion() ?></td>
            <td><?php echo $articulo->getDescuento() ?></td>
            <td><?php echo $articulo->getEnvio() ?></td>

                <td><?php echo $this->tag->linkTo(["articulo/edit/" . $articulo->getCodigoCategoria(), "Edit"]); ?></td>
                <td><?php echo $this->tag->linkTo(["articulo/delete/" . $articulo->getCodigoCategoria(), "Delete"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo(["articulo/search", "First", 'class' => 'page-link']) ?></li>
                <li><?php echo $this->tag->linkTo(["articulo/search?page=" . $page->before, "Previous", 'class' => 'page-link']) ?></li>
                <li><?php echo $this->tag->linkTo(["articulo/search?page=" . $page->next, "Next", 'class' => 'page-link']) ?></li>
                <li><?php echo $this->tag->linkTo(["articulo/search?page=" . $page->last, "Last", 'class' => 'page-link']) ?></li>
            </ul>
        </nav>
    </div>
</div>
